// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class ConvertPrivateKeyRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):ConvertPrivateKeyRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsConvertPrivateKeyRequest(bb:flatbuffers.ByteBuffer, obj?:ConvertPrivateKeyRequest):ConvertPrivateKeyRequest {
  return (obj || new ConvertPrivateKeyRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsConvertPrivateKeyRequest(bb:flatbuffers.ByteBuffer, obj?:ConvertPrivateKeyRequest):ConvertPrivateKeyRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ConvertPrivateKeyRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

privateKey():string|null
privateKey(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
privateKey(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startConvertPrivateKeyRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addPrivateKey(builder:flatbuffers.Builder, privateKeyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, privateKeyOffset, 0);
}

static endConvertPrivateKeyRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createConvertPrivateKeyRequest(builder:flatbuffers.Builder, privateKeyOffset:flatbuffers.Offset):flatbuffers.Offset {
  ConvertPrivateKeyRequest.startConvertPrivateKeyRequest(builder);
  ConvertPrivateKeyRequest.addPrivateKey(builder, privateKeyOffset);
  return ConvertPrivateKeyRequest.endConvertPrivateKeyRequest(builder);
}
}
