// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class ConvertJWTRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ConvertJWTRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsConvertJWTRequest(bb:flatbuffers.ByteBuffer, obj?:ConvertJWTRequest):ConvertJWTRequest {
  return (obj || new ConvertJWTRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsConvertJWTRequest(bb:flatbuffers.ByteBuffer, obj?:ConvertJWTRequest):ConvertJWTRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ConvertJWTRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

data():string|null
data(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
data(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

keyId():string|null
keyId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
keyId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startConvertJWTRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addData(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, dataOffset, 0);
}

static addKeyId(builder:flatbuffers.Builder, keyIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, keyIdOffset, 0);
}

static endConvertJWTRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createConvertJWTRequest(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset, keyIdOffset:flatbuffers.Offset):flatbuffers.Offset {
  ConvertJWTRequest.startConvertJWTRequest(builder);
  ConvertJWTRequest.addData(builder, dataOffset);
  ConvertJWTRequest.addKeyId(builder, keyIdOffset);
  return ConvertJWTRequest.endConvertJWTRequest(builder);
}
}
