// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class ConvertKeyPairRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ConvertKeyPairRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsConvertKeyPairRequest(bb:flatbuffers.ByteBuffer, obj?:ConvertKeyPairRequest):ConvertKeyPairRequest {
  return (obj || new ConvertKeyPairRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsConvertKeyPairRequest(bb:flatbuffers.ByteBuffer, obj?:ConvertKeyPairRequest):ConvertKeyPairRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ConvertKeyPairRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

privateKey():string|null
privateKey(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
privateKey(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

certificate():string|null
certificate(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
certificate(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

password():string|null
password(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
password(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startConvertKeyPairRequest(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addPrivateKey(builder:flatbuffers.Builder, privateKeyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, privateKeyOffset, 0);
}

static addCertificate(builder:flatbuffers.Builder, certificateOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, certificateOffset, 0);
}

static addPassword(builder:flatbuffers.Builder, passwordOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, passwordOffset, 0);
}

static endConvertKeyPairRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createConvertKeyPairRequest(builder:flatbuffers.Builder, privateKeyOffset:flatbuffers.Offset, certificateOffset:flatbuffers.Offset, passwordOffset:flatbuffers.Offset):flatbuffers.Offset {
  ConvertKeyPairRequest.startConvertKeyPairRequest(builder);
  ConvertKeyPairRequest.addPrivateKey(builder, privateKeyOffset);
  ConvertKeyPairRequest.addCertificate(builder, certificateOffset);
  ConvertKeyPairRequest.addPassword(builder, passwordOffset);
  return ConvertKeyPairRequest.endConvertKeyPairRequest(builder);
}
}
