// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class DecryptPrivateKeyRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DecryptPrivateKeyRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDecryptPrivateKeyRequest(bb:flatbuffers.ByteBuffer, obj?:DecryptPrivateKeyRequest):DecryptPrivateKeyRequest {
  return (obj || new DecryptPrivateKeyRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDecryptPrivateKeyRequest(bb:flatbuffers.ByteBuffer, obj?:DecryptPrivateKeyRequest):DecryptPrivateKeyRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DecryptPrivateKeyRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

privateKeyEncrypted():string|null
privateKeyEncrypted(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
privateKeyEncrypted(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

password():string|null
password(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
password(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startDecryptPrivateKeyRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addPrivateKeyEncrypted(builder:flatbuffers.Builder, privateKeyEncryptedOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, privateKeyEncryptedOffset, 0);
}

static addPassword(builder:flatbuffers.Builder, passwordOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, passwordOffset, 0);
}

static endDecryptPrivateKeyRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDecryptPrivateKeyRequest(builder:flatbuffers.Builder, privateKeyEncryptedOffset:flatbuffers.Offset, passwordOffset:flatbuffers.Offset):flatbuffers.Offset {
  DecryptPrivateKeyRequest.startDecryptPrivateKeyRequest(builder);
  DecryptPrivateKeyRequest.addPrivateKeyEncrypted(builder, privateKeyEncryptedOffset);
  DecryptPrivateKeyRequest.addPassword(builder, passwordOffset);
  return DecryptPrivateKeyRequest.endDecryptPrivateKeyRequest(builder);
}
}
