// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class DecryptPKCS1v15Request {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DecryptPKCS1v15Request {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDecryptPKCS1v15Request(bb:flatbuffers.ByteBuffer, obj?:DecryptPKCS1v15Request):DecryptPKCS1v15Request {
  return (obj || new DecryptPKCS1v15Request()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDecryptPKCS1v15Request(bb:flatbuffers.ByteBuffer, obj?:DecryptPKCS1v15Request):DecryptPKCS1v15Request {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DecryptPKCS1v15Request()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

ciphertext():string|null
ciphertext(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
ciphertext(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

privateKey():string|null
privateKey(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
privateKey(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startDecryptPKCS1v15Request(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addCiphertext(builder:flatbuffers.Builder, ciphertextOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, ciphertextOffset, 0);
}

static addPrivateKey(builder:flatbuffers.Builder, privateKeyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, privateKeyOffset, 0);
}

static endDecryptPKCS1v15Request(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDecryptPKCS1v15Request(builder:flatbuffers.Builder, ciphertextOffset:flatbuffers.Offset, privateKeyOffset:flatbuffers.Offset):flatbuffers.Offset {
  DecryptPKCS1v15Request.startDecryptPKCS1v15Request(builder);
  DecryptPKCS1v15Request.addCiphertext(builder, ciphertextOffset);
  DecryptPKCS1v15Request.addPrivateKey(builder, privateKeyOffset);
  return DecryptPKCS1v15Request.endDecryptPKCS1v15Request(builder);
}
}
