// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class EncryptPKCS1v15Request {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):EncryptPKCS1v15Request {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEncryptPKCS1v15Request(bb:flatbuffers.ByteBuffer, obj?:EncryptPKCS1v15Request):EncryptPKCS1v15Request {
  return (obj || new EncryptPKCS1v15Request()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEncryptPKCS1v15Request(bb:flatbuffers.ByteBuffer, obj?:EncryptPKCS1v15Request):EncryptPKCS1v15Request {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new EncryptPKCS1v15Request()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

message():string|null
message(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
message(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

publicKey():string|null
publicKey(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
publicKey(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startEncryptPKCS1v15Request(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addMessage(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, messageOffset, 0);
}

static addPublicKey(builder:flatbuffers.Builder, publicKeyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, publicKeyOffset, 0);
}

static endEncryptPKCS1v15Request(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createEncryptPKCS1v15Request(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset, publicKeyOffset:flatbuffers.Offset):flatbuffers.Offset {
  EncryptPKCS1v15Request.startEncryptPKCS1v15Request(builder);
  EncryptPKCS1v15Request.addMessage(builder, messageOffset);
  EncryptPKCS1v15Request.addPublicKey(builder, publicKeyOffset);
  return EncryptPKCS1v15Request.endEncryptPKCS1v15Request(builder);
}
}
