// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class MetadataPrivateKeyRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MetadataPrivateKeyRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMetadataPrivateKeyRequest(bb:flatbuffers.ByteBuffer, obj?:MetadataPrivateKeyRequest):MetadataPrivateKeyRequest {
  return (obj || new MetadataPrivateKeyRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMetadataPrivateKeyRequest(bb:flatbuffers.ByteBuffer, obj?:MetadataPrivateKeyRequest):MetadataPrivateKeyRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MetadataPrivateKeyRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

privateKey():string|null
privateKey(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
privateKey(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startMetadataPrivateKeyRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addPrivateKey(builder:flatbuffers.Builder, privateKeyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, privateKeyOffset, 0);
}

static endMetadataPrivateKeyRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMetadataPrivateKeyRequest(builder:flatbuffers.Builder, privateKeyOffset:flatbuffers.Offset):flatbuffers.Offset {
  MetadataPrivateKeyRequest.startMetadataPrivateKeyRequest(builder);
  MetadataPrivateKeyRequest.addPrivateKey(builder, privateKeyOffset);
  return MetadataPrivateKeyRequest.endMetadataPrivateKeyRequest(builder);
}
}
