// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { PKCS12KeyPair } from '../model/p-k-c-s12-key-pair';


export class PKCS12KeyPairResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):PKCS12KeyPairResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPKCS12KeyPairResponse(bb:flatbuffers.ByteBuffer, obj?:PKCS12KeyPairResponse):PKCS12KeyPairResponse {
  return (obj || new PKCS12KeyPairResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPKCS12KeyPairResponse(bb:flatbuffers.ByteBuffer, obj?:PKCS12KeyPairResponse):PKCS12KeyPairResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PKCS12KeyPairResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

output(obj?:PKCS12KeyPair):PKCS12KeyPair|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new PKCS12KeyPair()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

error():string|null
error(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
error(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startPKCS12KeyPairResponse(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addOutput(builder:flatbuffers.Builder, outputOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, outputOffset, 0);
}

static addError(builder:flatbuffers.Builder, errorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, errorOffset, 0);
}

static endPKCS12KeyPairResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPKCS12KeyPairResponse(builder:flatbuffers.Builder, outputOffset:flatbuffers.Offset, errorOffset:flatbuffers.Offset):flatbuffers.Offset {
  PKCS12KeyPairResponse.startPKCS12KeyPairResponse(builder);
  PKCS12KeyPairResponse.addOutput(builder, outputOffset);
  PKCS12KeyPairResponse.addError(builder, errorOffset);
  return PKCS12KeyPairResponse.endPKCS12KeyPairResponse(builder);
}
}
