// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class PublicKeyInfo {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PublicKeyInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPublicKeyInfo(bb:flatbuffers.ByteBuffer, obj?:PublicKeyInfo):PublicKeyInfo {
  return (obj || new PublicKeyInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPublicKeyInfo(bb:flatbuffers.ByteBuffer, obj?:PublicKeyInfo):PublicKeyInfo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PublicKeyInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

bitLen():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

mutate_bit_len(value:bigint):boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);

  if (offset === 0) {
    return false;
  }

  this.bb!.writeInt64(this.bb_pos + offset, value);
  return true;
}

size():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

mutate_size(value:bigint):boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);

  if (offset === 0) {
    return false;
  }

  this.bb!.writeInt64(this.bb_pos + offset, value);
  return true;
}

e():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

mutate_e(value:bigint):boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);

  if (offset === 0) {
    return false;
  }

  this.bb!.writeInt64(this.bb_pos + offset, value);
  return true;
}

static startPublicKeyInfo(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addBitLen(builder:flatbuffers.Builder, bitLen:bigint) {
  builder.addFieldInt64(0, bitLen, BigInt('0'));
}

static addSize(builder:flatbuffers.Builder, size:bigint) {
  builder.addFieldInt64(1, size, BigInt('0'));
}

static addE(builder:flatbuffers.Builder, e:bigint) {
  builder.addFieldInt64(2, e, BigInt('0'));
}

static endPublicKeyInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPublicKeyInfo(builder:flatbuffers.Builder, bitLen:bigint, size:bigint, e:bigint):flatbuffers.Offset {
  PublicKeyInfo.startPublicKeyInfo(builder);
  PublicKeyInfo.addBitLen(builder, bitLen);
  PublicKeyInfo.addSize(builder, size);
  PublicKeyInfo.addE(builder, e);
  return PublicKeyInfo.endPublicKeyInfo(builder);
}
}
