// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Hash } from '../model/hash';


export class SignPKCS1v15Request {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):SignPKCS1v15Request {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSignPKCS1v15Request(bb:flatbuffers.ByteBuffer, obj?:SignPKCS1v15Request):SignPKCS1v15Request {
  return (obj || new SignPKCS1v15Request()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSignPKCS1v15Request(bb:flatbuffers.ByteBuffer, obj?:SignPKCS1v15Request):SignPKCS1v15Request {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SignPKCS1v15Request()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

message():string|null
message(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
message(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

hash():Hash {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : Hash.MD5;
}

mutate_hash(value:Hash):boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);

  if (offset === 0) {
    return false;
  }

  this.bb!.writeInt32(this.bb_pos + offset, value);
  return true;
}

privateKey():string|null
privateKey(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
privateKey(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startSignPKCS1v15Request(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addMessage(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, messageOffset, 0);
}

static addHash(builder:flatbuffers.Builder, hash:Hash) {
  builder.addFieldInt32(1, hash, Hash.MD5);
}

static addPrivateKey(builder:flatbuffers.Builder, privateKeyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, privateKeyOffset, 0);
}

static endSignPKCS1v15Request(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSignPKCS1v15Request(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset, hash:Hash, privateKeyOffset:flatbuffers.Offset):flatbuffers.Offset {
  SignPKCS1v15Request.startSignPKCS1v15Request(builder);
  SignPKCS1v15Request.addMessage(builder, messageOffset);
  SignPKCS1v15Request.addHash(builder, hash);
  SignPKCS1v15Request.addPrivateKey(builder, privateKeyOffset);
  return SignPKCS1v15Request.endSignPKCS1v15Request(builder);
}
}
