// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Hash } from '../model/hash';
import { SaltLength } from '../model/salt-length';


export class SignPSSBytesRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):SignPSSBytesRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSignPSSBytesRequest(bb:flatbuffers.ByteBuffer, obj?:SignPSSBytesRequest):SignPSSBytesRequest {
  return (obj || new SignPSSBytesRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSignPSSBytesRequest(bb:flatbuffers.ByteBuffer, obj?:SignPSSBytesRequest):SignPSSBytesRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SignPSSBytesRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

message(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

messageLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

messageArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

hash():Hash {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : Hash.MD5;
}

mutate_hash(value:Hash):boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);

  if (offset === 0) {
    return false;
  }

  this.bb!.writeInt32(this.bb_pos + offset, value);
  return true;
}

saltLength():SaltLength {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : SaltLength.AUTO;
}

mutate_saltLength(value:SaltLength):boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);

  if (offset === 0) {
    return false;
  }

  this.bb!.writeInt32(this.bb_pos + offset, value);
  return true;
}

privateKey():string|null
privateKey(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
privateKey(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startSignPSSBytesRequest(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addMessage(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, messageOffset, 0);
}

static createMessageVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startMessageVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addHash(builder:flatbuffers.Builder, hash:Hash) {
  builder.addFieldInt32(1, hash, Hash.MD5);
}

static addSaltLength(builder:flatbuffers.Builder, saltLength:SaltLength) {
  builder.addFieldInt32(2, saltLength, SaltLength.AUTO);
}

static addPrivateKey(builder:flatbuffers.Builder, privateKeyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, privateKeyOffset, 0);
}

static endSignPSSBytesRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSignPSSBytesRequest(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset, hash:Hash, saltLength:SaltLength, privateKeyOffset:flatbuffers.Offset):flatbuffers.Offset {
  SignPSSBytesRequest.startSignPSSBytesRequest(builder);
  SignPSSBytesRequest.addMessage(builder, messageOffset);
  SignPSSBytesRequest.addHash(builder, hash);
  SignPSSBytesRequest.addSaltLength(builder, saltLength);
  SignPSSBytesRequest.addPrivateKey(builder, privateKeyOffset);
  return SignPSSBytesRequest.endSignPSSBytesRequest(builder);
}
}
